using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Security.Authentication;
using System.Threading;
using System.Threading.Tasks;
using RtspClientSharp.MediaParsers;
using RtspClientSharp.RawFrames;
using RtspClientSharp.Rtp;
using RtspClientSharp.Rtsp;
using RtspClientSharp.Ts;
using RtspClientSharp.Utils;

namespace RtspClientSharp.RtpClient
{
    public sealed class RtpClient : IRtpClient
    {
        private const int UdpSocketReceiveBufferSize = 512 * 1024;
        private bool _anyFrameReceived;
        private UdpClient _rtpClient;
        private int _disposed;
        private long _receivedDatagramCount;
        private long _generatedFrameCount;
        private long _dispatcherDroppedFrameCount;
        private readonly byte[] _receiveBuffer = new byte[Constants.UdpReceiveBufferSize];
        public ConnectionParameters ConnectionParameters { get; }
        public int Timeout { get; set; } = 3000;

        public event Action<RawFrame> RawFrameReceived;
        public event EventHandler<RawFrame> RawFrameGenerated;
        public event EventHandler<RawFrame> FrameReceived;
        public bool IsH264 { get; set; } = true;
        /// <summary>
        /// The media packet format selected for the current direct UDP session.
        /// This is <see cref="MediaTransportMode.Auto"/> until the first datagram
        /// is classified.
        /// </summary>
        public MediaTransportMode DetectedTransportMode =>
            stream is AutoDetectingTransportStream autoStream
                ? autoStream.DetectedMode
                : MediaTransportMode.Auto;
        /// <summary>
        /// Optional Annex-B SPS/PPS bytes for a direct RTP H.264 stream. Direct RTP has no
        /// SDP exchange, so this must be supplied when the sender does not repeat them in-band.
        /// </summary>
        public byte[] H264SpsPpsBytes { get; set; } = Array.Empty<byte>();
        /// <summary>Number of non-empty UDP datagrams read by this client.</summary>
        public long ReceivedDatagramCount => Interlocked.Read(ref _receivedDatagramCount);
        /// <summary>Number of complete media frames generated by the parser.</summary>
        public long GeneratedFrameCount => Interlocked.Read(ref _generatedFrameCount);
        /// <summary>Number of parsed frames rejected by the bounded dispatcher.</summary>
        public long DispatcherDroppedFrameCount => Interlocked.Read(ref _dispatcherDroppedFrameCount);

        private ITransportStream stream;
        private readonly RawFrameDispatcher _frameDispatcher;

        public RtpClient(ConnectionParameters connectionParameters)
        {
            ConnectionParameters = connectionParameters ??
                                   throw new ArgumentNullException(nameof(connectionParameters));

            RawFrameReceived = frame =>
            {
                Volatile.Write(ref _anyFrameReceived, true);
                FrameReceived?.Invoke(this, frame);
            };

            _frameDispatcher = new RawFrameDispatcher(frame => RawFrameReceived?.Invoke(frame));
        }

        ~RtpClient()
        {
            Dispose();
        }

        /// <summary>
        /// Connect to endpoint and start RTSP session
        /// </summary>
        /// <exception cref="OperationCanceledException"></exception>
        /// <exception cref="InvalidCredentialException"></exception>
        /// <exception cref="RtspClientException"></exception>
        public async Task ConnectAsync(CancellationToken token)
        {
            await Task.Run(async () =>
            {
                _rtpClient = CreateRtpClientInternal(ConnectionParameters.ConnectionUri.Host, ConnectionParameters.ConnectionUri.Port);

                try
                {
                    Task connectionTask = SetupConnection();

                    if (connectionTask.IsCompleted)
                    {
                        await connectionTask;
                        return;
                    }

                    var delayTaskCancelTokenSource = new CancellationTokenSource();
                    using (var linkedTokenSource =
                        CancellationTokenSource.CreateLinkedTokenSource(delayTaskCancelTokenSource.Token, token))
                    {
                        CancellationToken delayTaskToken = linkedTokenSource.Token;

                        Task delayTask = Task.Delay(Timeout, delayTaskToken);

                        if (connectionTask != await Task.WhenAny(connectionTask, delayTask))
                        {
                            connectionTask.IgnoreExceptions();

                            if (delayTask.IsCanceled)
                                throw new OperationCanceledException();

                            throw new TimeoutException();
                        }

                        delayTaskCancelTokenSource.Cancel();
                        await connectionTask;
                    }
                }
                catch (Exception e)
                {
                    _rtpClient.Dispose();
                    Volatile.Write(ref _rtpClient, null);

                    if (e is TimeoutException)
                        throw new RtspClientException("Connection timeout", e);

                    if (e is OperationCanceledException)
                        throw;

                    if (!(e is RtspClientException))
                        throw new RtspClientException("Connection error", e);

                    throw;
                }
            }, token).ConfigureAwait(false);
        }

        private Task SetupConnection()
        {
            Codecs.CodecInfo info;
            if (IsH264)
            {
                info = new Codecs.Video.H264CodecInfo
                {
                    SpsPpsBytes = H264SpsPpsBytes ?? Array.Empty<byte>()
                };
            }
            else
            {
                info = new Codecs.Video.MJPEGCodecInfo();
            }

            IMediaPayloadParser mediaPayloadParser = MediaPayloadParser.CreateFrom(info);

            IRtpSequenceAssembler rtpSequenceAssembler =
                new RtpSequenceAssembler(Constants.UdpReceiveBufferSize, 256);
            mediaPayloadParser.FrameGenerated = OnFrameGeneratedThreadSafe;

            Func<ITransportStream> rtpStreamFactory = () =>
                new RtpStream(mediaPayloadParser, 90000, rtpSequenceAssembler);
            Func<ITransportStream> mpegTsStreamFactory = () => new TsStream(mediaPayloadParser);

            stream = new AutoDetectingTransportStream(ConnectionParameters.TransportMode,
                rtpStreamFactory, mpegTsStreamFactory);

            return Task.CompletedTask;
        }

        private async Task ReceiveRtpFromUdpAsync()
        {
            int bytesRead = await _rtpClient.Client.ReceiveAsync(
                new ArraySegment<byte>(_receiveBuffer), SocketFlags.None).ConfigureAwait(false);

            if (bytesRead == 0)
                return;

            Interlocked.Increment(ref _receivedDatagramCount);
            stream.Process(new ArraySegment<byte>(_receiveBuffer, 0, bytesRead));
        }

        /// <summary>
        /// Receive frames. 
        /// Should be called after successful connection to endpoint or InvalidOperationException will be thrown
        /// </summary>
        /// <exception cref="OperationCanceledException"></exception>
        /// <exception cref="RtspClientException"></exception>
        /// <exception cref="InvalidOperationException"></exception>
        public async Task ReceiveAsync(CancellationToken token)
        {
            if (_rtpClient == null)
                throw new InvalidOperationException("Client should be connected first");

            try
            {
                Task receiveInternalTask = ReceiveRtpFromUdpAsync();

                if (receiveInternalTask.IsCompleted)
                {
                    await receiveInternalTask;
                    return;
                }

                var delayTaskCancelTokenSource = new CancellationTokenSource();
                using (var linkedTokenSource =
                    CancellationTokenSource.CreateLinkedTokenSource(delayTaskCancelTokenSource.Token, token))
                {
                    CancellationToken delayTaskToken = linkedTokenSource.Token;

                    while (true)
                    {
                        _anyFrameReceived = false;

                        Task result = await Task.WhenAny(receiveInternalTask,
                            Task.Delay(Timeout, delayTaskToken)).ConfigureAwait(false);

                        if (result == receiveInternalTask)
                        {
                            delayTaskCancelTokenSource.Cancel();
                            await receiveInternalTask;
                            break;
                        }

                        if (result.IsCanceled)
                        {
                            TimeSpan cancelTimeout = new TimeSpan(0, 0, 0, 0, Timeout);
                            if (cancelTimeout == TimeSpan.Zero ||
                                await Task.WhenAny(receiveInternalTask,
                                    Task.Delay(cancelTimeout, CancellationToken.None)) != receiveInternalTask)
                                _rtpClient.Dispose();

                            await Task.WhenAny(receiveInternalTask);
                            throw new OperationCanceledException();
                        }

                        if (!Volatile.Read(ref _anyFrameReceived))
                        {
                            receiveInternalTask.IgnoreExceptions();
                            throw new RtspClientException("Receive timeout", new TimeoutException());
                        }
                    }
                }
            }
            catch (InvalidOperationException)
            {
                throw;
            }
            catch (OperationCanceledException)
            {
                throw;
            }
            catch (Exception e)
            {
                throw new RtspClientException("Receive error", e);
            }
            //finally
            //{
            //    _rtpClient.Dispose();
            //    Volatile.Write(ref _rtpClient, null);
            //}
        }

        /// <summary>
        /// Clean up unmanaged resources
        /// </summary>
        public void Dispose()
        {
            if (Interlocked.CompareExchange(ref _disposed, 1, 0) != 0)
                return;

            _frameDispatcher.Dispose();
            _rtpClient?.Dispose();

            GC.SuppressFinalize(this);
        }

        private UdpClient CreateRtpClientInternal(string ip, int port)
        {
            var client = new UdpClient();
            // A single encoded video frame can arrive as a burst of RTP datagrams. Keep
            // enough kernel-side queue space to absorb that burst while the parser and
            // frame dispatcher process the previous datagram.
            client.Client.ReceiveBufferSize = UdpSocketReceiveBufferSize;
            if (ip != null)
            {
                IPAddress address = IPAddress.Parse(ip);

                try
                {
                    client.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseUnicastPort, true);
                }
                catch
                {
                    client.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
                }

                client.Client.Bind(new IPEndPoint(IPAddress.Any, port));

                if (IsMulticast(address))
                {
                    JoinMulticastGroup(client, address);
                }

                //if(address.Address == IPAddress.Broadcast.Address)
                //{
                //    client.EnableBroadcast = true;
                //}
            }

            return client;
        }

        private void JoinMulticastGroup(UdpClient client, IPAddress multicastAddress)
        {
            IPAddress multicastInterfaceAddress = ConnectionParameters.MulticastInterfaceAddress;
            if (multicastInterfaceAddress != null)
            {
                client.JoinMulticastGroup(multicastAddress, multicastInterfaceAddress);
                return;
            }

            if (multicastAddress.AddressFamily == AddressFamily.InterNetworkV6)
            {
                foreach (int i in GetMulticastCapableInterfaceIndex())
                    client.JoinMulticastGroup(i, multicastAddress);

                return;
            }

            IPAddress[] interfaces = GetMulticastCapableInterface();
            if (interfaces.Length == 0)
            {
                client.JoinMulticastGroup(multicastAddress);
                return;
            }

            Exception lastException = null;
            bool joined = false;

            foreach (IPAddress localAddress in interfaces)
            {
                try
                {
                    client.JoinMulticastGroup(multicastAddress, localAddress);
                    joined = true;
                }
                catch (Exception e) when (e is SocketException || e is ArgumentException)
                {
                    lastException = e;
                }
            }

            if (!joined && lastException != null)
                throw lastException;
        }


        private void OnFrameGeneratedThreadSafe(RawFrame frame)
        {
            Interlocked.Increment(ref _generatedFrameCount);
            if (RawFrameReceived == null)
                return;

            // Copy and dispatch outside the receive thread. FrameSegment points into parser
            // storage that is reused for the next frame, so the dispatcher owns the copy.
            Volatile.Write(ref _anyFrameReceived, true);
            RaiseRawFrameGenerated(frame);
            if (!_frameDispatcher.TryEnqueue(frame))
                Interlocked.Increment(ref _dispatcherDroppedFrameCount);
        }

        private void RaiseRawFrameGenerated(RawFrame frame)
        {
            try
            {
                RawFrameGenerated?.Invoke(this, frame);
            }
            catch (Exception exception)
            {
                // A tap such as recording must not be able to terminate the
                // receive/parser path. The subscriber owns its error reporting.
                System.Diagnostics.Debug.WriteLine(exception);
            }
        }

        static bool IsMulticast(IPAddress ip)
        {
            if(ip.AddressFamily == AddressFamily.InterNetwork)
            {
                byte firstOctet = ip.GetAddressBytes()[0];
                return firstOctet >= 224 && firstOctet <= 239;
            }
            else if (ip.AddressFamily == AddressFamily.InterNetworkV6)
            {
                return ip.IsIPv6Multicast;
            }

            return false;
        }

        private static IPAddress[] GetMulticastCapableInterface()
        {
            List<IPAddress> list = new List<IPAddress>();
            foreach (NetworkInterface ni in NetworkInterface.GetAllNetworkInterfaces())
            {
                if (ni.OperationalStatus != OperationalStatus.Up) continue;

                if (ni.NetworkInterfaceType == NetworkInterfaceType.Loopback ||
                   ni.NetworkInterfaceType == NetworkInterfaceType.Tunnel) continue;

                if (!ni.SupportsMulticast) continue;

                if (ni.Description.ToLower().Contains("virtual") || ni.Name.ToLower().Contains("vmware")) continue;

                var ipProps = ni.GetIPProperties();
                foreach (var ip in ipProps.UnicastAddresses)
                {
                    if (ip.Address.AddressFamily == AddressFamily.InterNetwork && !IPAddress.IsLoopback(ip.Address))
                    {
                        list.Add(ip.Address);
                    }
                }
            }

            return list.ToArray();
        }

        private static int[] GetMulticastCapableInterfaceIndex()
        {
            List<int> list = new List<int>();
            foreach (NetworkInterface ni in NetworkInterface.GetAllNetworkInterfaces())
            {
                if (ni.OperationalStatus != OperationalStatus.Up) continue;

                if (ni.NetworkInterfaceType == NetworkInterfaceType.Loopback ||
                   ni.NetworkInterfaceType == NetworkInterfaceType.Tunnel) continue;

                if (!ni.SupportsMulticast) continue;

                string desc = ni.Description.ToLower();
                string name = ni.Name.ToLower();
                if (desc.Contains("virtual") ||
                   name.Contains("vmware")) continue;

                var ipProps = ni.GetIPProperties();
                IPv4InterfaceProperties ipv4Props = ipProps.GetIPv4Properties();
                if (ipv4Props == null) continue;

                foreach (var ip in ipProps.UnicastAddresses)
                {
                    if (ip.Address.AddressFamily != AddressFamily.InterNetwork) continue;
                    if (IPAddress.IsLoopback(ip.Address)) continue;

                    list.Add(ipv4Props.Index);
                    break;
                }
            }

            return list.ToArray();
        }
    }
}
